{{- if .Values.externalSecrets.enabled }}
{{- range $name, $config := .Values.externalSecrets }}
{{- if ne $name "enabled" }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $config.secretStoreRef.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "go-htmx-fiber.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
{{- break }}
{{- end }}
{{- end }}
{{- end }}

